easy_admin:
    site_name: 'Symfony template'
    design:
            form_theme: 'vertical'
            brand_color: '#212121'
            color_scheme: 'dark'
    entities:
         City:
              class: AppBundle\Entity\City
              title: 'Cities'
              form:
                  fields:
                      - { property: 'cityName', label: 'Name of the city'}
                      - { property: 'cityCountry', label: 'Country where the city is located'}
                      - { property: 'cityText', label: 'Description about the city'}
                      - { property: 'cityImageFile', type: 'vich_image', base_path: '%app.path.product_images%', label: 'Image of the city' }
              list:
                  title: "Cities"
                  fields:
                     - { property: 'cityName', label: 'Name of the city'}
                     - { property: 'cityCountry', label: 'Country where the city is located'}
                     - { property: 'cityText', label: 'Description about the city'}
                     - { property: 'cityImage', type: 'vich_image', base_path: '%app.path.product_images%', label: 'Image of the city' }